In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

In [5]:
df = pd.read_csv('C:\Users\hp\Desktop\Python project\dataset\Algerian_forest_fires_cleaned_dataset.csv')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (892691456.py, line 1)

In [ ]:
df

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,26,9,2012,30,65,14,0.0,85.4,16.0,44.5,4.5,16.9,6.5,fire,1
239,27,9,2012,28,87,15,4.4,41.1,6.5,8.0,0.1,6.2,0.0,not fire,1
240,28,9,2012,27,87,29,0.5,45.9,3.5,7.9,0.4,3.4,0.2,not fire,1
241,29,9,2012,24,54,18,0.1,79.7,4.3,15.2,1.7,5.1,0.7,not fire,1
242,30,9,2012,24,64,15,0.2,67.3,3.8,16.5,1.2,4.8,0.5,not fire,1

In [ ]:
df.drop(['day', 'month', 'year'],axis=1, inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 243 entries, 0 to 242
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  243 non-null    int64
 1   RH           243 non-null    int64
 2   Ws           243 non-null    int64
 3   Rain         243 non-null    float64
 4   FFMC         243 non-null    float64
 5   DMC          243 non-null    float64
 6   DC           243 non-null    float64
 7   ISI          243 non-null    float64
 8   BUI          243 non-null    float64
 9   FWI          243 non-null    float64
 10  Classes      243 non-null    object
 11  Region       243 non-null    int64
dtypes: float64(7), int64(4), object(1)
memory usage: 22.9+ KB

In [ ]:
df.describe()

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Region
count,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000,243.000000
mean,32.152263,62.041152,15.493827,0.762963,77.842387,14.680658,49.430864,4.742387,16.690535,7.035391,0.497942
std,3.628039,14.828160,2.811385,2.003207,14.349641,12.393040,47.665606,4.154234,14.228421,7.440568,0.501028
min,22.000000,21.000000,6.000000,0.000000,28.600000,0.700000,6.900000,0.000000,1.100000,0.000000,0.000000
25%,30.000000,52.500000,14.000000,0.000000,71.850000,5.800000,12.350000,1.400000,6.000000,0.700000,0.000000
50%,32.000000,63.000000,15.000000,0.000000,83.300000,11.300000,33.100000,3.500000,12.400000,4.200000,0.000000
75%,35.000000,73.500000,17.000000,0.500000,88.300000,20.800000,69.100000,7.250000,22.650000,11.450000,1.000000
max,42.000000,90.000000,29.000000,16.800000,96.000000,65.900000,220.400000,19.000000,68.000000,31.100000,1.000000

In [ ]:
df['Classes'].unique()

array(['not fire   ', 'fire   ', 'fire', 'fire ', 'not fire', 'not fire ',
       'not fire     ', 'not fire    '], dtype=object)

In [ ]:
df['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [ ]:
df['Classes'] = np.where(df['Classes'].str.contains('not fire'),0,1)

In [ ]:
df['Classes']

0      0
1      0
2      0
3      0
4      0
      ..
238    1
239    0
240    0
241    0
242    0
Name: Classes, Length: 243, dtype: int64

In [ ]:
df['Classes'].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64

In [ ]:
X = df.drop('FWI', axis=1)
y = df['FWI']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [ ]:
#there is problem with this data
#using heatmap we saw three features have multiple collinearity
#VIF technique (> 10 we generally drop those columns)

In [ ]:
sc= StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
lr= LinearRegression()
rd= Ridge()
ls = Lasso()
es = ElasticNet()

In [ ]:
lr.fit(X_train_sc,y_train) # training
y_pred_tr=lr.predict(X_train_sc) # prediction_training
y_pred_test=lr.predict(X_test_sc) # prediction_testing
print('Train Score',lr.score(X_train_sc,y_train)) # metric_chk_train
print('Test Score',lr.score(X_test_sc,y_test)) # metric_chk_test
print('Mean Absolute Error',mean_absolute_error(y_test,y_pred_test)) # mae for test
print('Mean Squared Error',mean_squared_error(y_test,y_pred_test))  # mse for test
print('Root Mean Squared Error',np.sqrt(mean_squared_error(y_test,y_pred_test))) #rmse for test
print('R2 Score',r2_score(y_test,y_pred_test)) # r2 for test

Train Score 0.9737558301667233
Test Score 0.9890356825759857
Mean Absolute Error 0.4267520614689853
Mean Squared Error 0.33231115384863824
Root Mean Squared Error 0.5764643560955337
R2 Score 0.9890356825759857

In [ ]:
rd.fit(X_train_sc,y_train) # training
y_pred_tr=rd.predict(X_train_sc) # prediction_training
y_pred_test=rd.predict(X_test_sc) # prediction_testing
print('Train Score',rd.score(X_train_sc,y_train)) # metric_chk_train
print('Test Score',rd.score(X_test_sc,y_test)) # metric_chk_test
print('Mean Absolute Error',mean_absolute_error(y_test,y_pred_test)) # mae for test
print('Mean Squared Error',mean_squared_error(y_test,y_pred_test))  # mse for test
print('Root Mean Squared Error',np.sqrt(mean_squared_error(y_test,y_pred_test))) #rmse for test
print('R2 Score',r2_score(y_test,y_pred_test)) # r2 for test

Train Score 0.9736662588815013
Test Score 0.9845121782477887
Mean Absolute Error 0.46348598120275497
Mean Squared Error 0.4694114296442019
Root Mean Squared Error 0.6851360665183245
R2 Score 0.9845121782477887

In [ ]:
ls.fit(X_train_sc,y_train) # training
y_pred_tr=ls.predict(X_train_sc) # prediction_training
y_pred_test=ls.predict(X_test_sc) # prediction_testing
print('Train Score',ls.score(X_train_sc,y_train)) # metric_chk_train
print('Test Score',ls.score(X_test_sc,y_test)) # metric_chk_test
print('Mean Absolute Error',mean_absolute_error(y_test,y_pred_test)) # mae for test
print('Mean Squared Error',mean_squared_error(y_test,y_pred_test))  # mse for test
print('Root Mean Squared Error',np.sqrt(mean_squared_error(y_test,y_pred_test))) #rmse for test
print('R2 Score',r2_score(y_test,y_pred_test)) # r2 for test

Train Score 0.9493233613044427
Test Score 0.9527917018651335
Mean Absolute Error 0.9552746314709515
Mean Squared Error 1.4308089977464673
Root Mean Squared Error 1.1961642854334296
R2 Score 0.9527917018651335

In [ ]:
es.fit(X_train_sc,y_train) # training
y_pred_tr=es.predict(X_train_sc) # prediction_training
y_pred_test=es.predict(X_test_sc) # prediction_testing
print('Train Score',es.score(X_train_sc,y_train)) # metric_chk_train
print('Test Score',es.score(X_test_sc,y_test)) # metric_chk_test
print('Mean Absolute Error',mean_absolute_error(y_test,y_pred_test)) # mae for test
print('Mean Squared Error',mean_squared_error(y_test,y_pred_test))  # mse for test
print('Root Mean Squared Error',np.sqrt(mean_squared_error(y_test,y_pred_test))) #rmse for test
print('R2 Score',r2_score(y_test,y_pred_test)) # r2 for test

Train Score 0.9121782316503868
Test Score 0.8829107841423941
Mean Absolute Error 1.5279150847018705
Mean Squared Error 3.5487893062683153
Root Mean Squared Error 1.8838230559870306
R2 Score 0.8829107841423941

In [ ]:
import pickle
pickle.dump(sc,open('scalar_project.pkl','wb'))
pickle.dump(rd,open('ridge_project.pkl','wb'))